// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Illustration struct {
	ID            int64              `json:"id"`
	Title         string             `json:"title"`
	Slug          pgtype.Text        `json:"slug"`
	Description   string             `json:"description"`
	Imageurl      string             `json:"imageurl"`
	Imageheight   pgtype.Int4        `json:"imageheight"`
	Imagewidth    pgtype.Int4        `json:"imagewidth"`
	Imagemimetype pgtype.Text        `json:"imagemimetype"`
	Imagefilesize pgtype.Int4        `json:"imagefilesize"`
	Post          pgtype.Text        `json:"post"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type IllustrationSoftware struct {
	IllustrationID int64 `json:"illustration_id"`
	SoftwareID     int64 `json:"software_id"`
}

type Software struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Image     pgtype.Text        `json:"image"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
