// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Illustration struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Imageurl    string             `json:"imageurl"`
	Post        pgtype.Text        `json:"post"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
