// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIllustration = `-- name: CreateIllustration :one
INSERT INTO illustrations (
    title,
    slug,
    description,
    imageURL,
    post,
    finished_at
) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, title, slug, description, imageurl, post, finished_at, created_at
`

type CreateIllustrationParams struct {
	Title       string             `json:"title"`
	Slug        pgtype.Text        `json:"slug"`
	Description string             `json:"description"`
	Imageurl    string             `json:"imageurl"`
	Post        pgtype.Text        `json:"post"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) CreateIllustration(ctx context.Context, arg CreateIllustrationParams) (Illustration, error) {
	row := q.db.QueryRow(ctx, createIllustration,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Imageurl,
		arg.Post,
		arg.FinishedAt,
	)
	var i Illustration
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Imageurl,
		&i.Post,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findIllustrationById = `-- name: FindIllustrationById :one
SELECT id, title, slug, description, imageurl, post, finished_at, created_at FROM illustrations WHERE id = $1
`

func (q *Queries) FindIllustrationById(ctx context.Context, id int64) (Illustration, error) {
	row := q.db.QueryRow(ctx, findIllustrationById, id)
	var i Illustration
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Imageurl,
		&i.Post,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findIllustrationByName = `-- name: FindIllustrationByName :one
SELECT id, title, slug, description, imageurl, post, finished_at, created_at FROM illustrations WHERE slug = $1 LIMIT 1
`

func (q *Queries) FindIllustrationByName(ctx context.Context, slug pgtype.Text) (Illustration, error) {
	row := q.db.QueryRow(ctx, findIllustrationByName, slug)
	var i Illustration
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Imageurl,
		&i.Post,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findIllustrationsCount = `-- name: FindIllustrationsCount :one
SELECT COUNT(*) FROM illustrations
`

func (q *Queries) FindIllustrationsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, findIllustrationsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listIllustrations = `-- name: ListIllustrations :many
SELECT id, title, slug, description, imageurl, post, finished_at, created_at 
FROM illustrations 
ORDER BY finished_at, created_at DESC
LIMIT $1 OFFSET $2
`

type ListIllustrationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListIllustrations(ctx context.Context, arg ListIllustrationsParams) ([]Illustration, error) {
	rows, err := q.db.Query(ctx, listIllustrations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Illustration
	for rows.Next() {
		var i Illustration
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Imageurl,
			&i.Post,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSlug = `-- name: UpdateSlug :one
UPDATE illustrations SET slug = $1 WHERE id = $2 RETURNING id, title, slug, description, imageurl, post, finished_at, created_at
`

type UpdateSlugParams struct {
	Slug pgtype.Text `json:"slug"`
	ID   int64       `json:"id"`
}

func (q *Queries) UpdateSlug(ctx context.Context, arg UpdateSlugParams) (Illustration, error) {
	row := q.db.QueryRow(ctx, updateSlug, arg.Slug, arg.ID)
	var i Illustration
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Imageurl,
		&i.Post,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}
